phrase:
  access_token: "b7fc60cd08e349735c546d147186900a91ec509bf763e515ea531affb3cd4c29"
  
  project_id: "3c7ad23566afde5d70c4afd7cfe77104"

  file_format: "properties"

  push:

    sources:

    - file: "./Jake_<locale_code>.properties"
    - autotranslate: true

  pull:

    targets:

    - file: "./Jake_<locale_code>.properties"
